### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'dot': 'dot'

### ISSUE THREAD

**Issue by kavinduravishka** [ertsiger/induction-subgoal-automata-rl#2]
I tried to run the following command.

`python3 run_isa.py hrl config/examples/officeworld/coffee_mail.json
`

And I got the following error

```
Traceback (most recent call last):
  File "run_isa.py", line 252, in <module>
    isa_algorithm.run(loaded_checkpoint)
  File "/path/to/folder/induction-subgoal-automata-rl/src/reinforcement_learning/isa_base_algorithm.py", line 130, in run
    super().run(loaded_checkpoint)
  File "/path/to/folder/induction-subgoal-automata-rl/src/reinforcement_learning/learning_algorithm.py", line 140, in run
    self._run_tasks()
  File "/path/to/folder/induction-subgoal-automata-rl/src/reinforcement_learning/learning_algorithm.py", line 148, in _run_tasks
    self._run_episode(self.current_domain_id, self.current_task_id)
  File "/path/to/folder/induction-subgoal-automata-rl/src/reinforcement_learning/isa_hrl_algorithm.py", line 268, in _run_episode
    return super()._run_episode(domain_id, task_id)
  File "/path/to/folder/induction-subgoal-automata-rl/src/reinforcement_learning/isa_base_algorithm.py", line 181, in _run_episode
    compressed_observation_history)
  File "/path/to/folder/induction-subgoal-automata-rl/src/reinforcement_learning/isa_base_algorithm.py", line 339, in _perform_interleaved_automaton_learning
    self._update_automaton(task, domain_id)
  File "/path/to/folder/induction-subgoal-automata-rl/src/reinforcement_learning/isa_base_algorithm.py", line 405, in _update_automaton
    ISAAlgorithmBase.AUTOMATON_PLOT_FILENAME % self.automaton_counters[domain_id])
  File "/path/to/virtual/env/lib/python3.6/site-packages/gym-subgoal-automata/gym_subgoal_automata/utils/subgoal_automaton.py", line 128, in plot
    self._run_graphviz_subprocess(diagram_path, solution_plot_path)
  File "/path/to/virtual/env/lib/python3.6/site-packages/gym-subgoal-automata/gym_subgoal_automata/utils/subgoal_automaton.py", line 193, in _run_graphviz_subprocess
    filename])
  File "/path/to/virtual/env/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/path/to/virtual/env/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/path/to/virtual/env/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dot': 'dot'
```
I tried to locate where the file name "dot" has been mentioned. But I couldn't find any. 

Can you please solve this bug or tell me what to do to solve this. Thank you.

**Comment by ertsiger** [comment]
Hi @kavinduravishka, sorry for not answering earlier. I was trying to reproduce the error from a fresh installation when I saw you had closed the issue. My suspicion is that you don't have Graphviz installed (the `.dot` file is an intermediate Graphviz file before producing the image, as far as I remember), but I wonder what the issue was in case someone faces it again.

Thanks.

**Comment by kavinduravishka** [comment]
Thank you for your quick response. Actually the problem was with `Graphviz` binaries as you said. I had to install them with `apt-get install graphviz` command. I think it will be useful for others if you can include that to the requirements list along with `ILASP` and `clingo` in README.md file.

**Comment by ertsiger** [comment]
Thanks @kavinduravishka, I'll add the command to the instructions now.
